# Generated by Django 4.2.3 on 2023-08-05 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_lesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='сумма')),
                ('method', models.CharField(choices=[('бзналичный', 'безналичный'), ('наличный', 'Наличные')], max_length=100, verbose_name='способ оплаты')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='курс')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
