# Generated by Django 4.2.3 on 2023-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('безналичный', 'безналичный'), ('наличный', 'Наличные')], max_length=100, verbose_name='способ оплаты'),
        ),
    ]
