# Generated by Django 4.2.3 on 2023-08-05 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 12, 16, 50, 169077), verbose_name='Дата и время'),
        ),
    ]
