# Generated by Django 4.2.3 on 2023-08-05 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_payment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 12, 19, 17, 285271, tzinfo=datetime.timezone.utc), verbose_name='Дата и время'),
        ),
    ]
