# Generated by Django 4.2.3 on 2023-08-05 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_payment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='main.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 12, 59, 6, 602660, tzinfo=datetime.timezone.utc), verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('безналичный', 'Безналичный'), ('наличный', 'Наличные')], max_length=100, verbose_name='способ оплаты'),
        ),
    ]
