# Generated by Django 4.2.3 on 2023-08-05 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_lesson_course_alter_payment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='main.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 13, 9, 55, 980806, tzinfo=datetime.timezone.utc), verbose_name='Дата и время'),
        ),
    ]
