# Generated by Django 4.2.3 on 2023-08-14 09:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0016_alter_payment_datetime_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 9, 4, 12, 567265, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.course",
                verbose_name="курс, related_name='subscription'",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
