# Generated by Django 4.2.3 on 2023-08-17 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_payment_datetime_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="оплачено"),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(
                default="NULL", max_length=100, verbose_name="id_платежа"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 17, 8, 50, 28, 925155, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время",
            ),
        ),
    ]
